
# name: remote ssh command
# on: [push]
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: executing remote ssh commands using ssh key
      uses: appleboy/scp-action@master
      env:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
#         port: ${{ secrets.PORT }}
        source: .
        target: "/home/autodeploy/prj"
        
    - name: multiple command
      uses: appleboy/ssh-action@master
      env:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
#         port: ${{ secrets.PORT }}
        script: |
          whoami
          ls -al

      
